//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string ACTION { get; set; }
        public Nullable<bool> USERS { get; set; }
        public Nullable<bool> PROFESSORS { get; set; }
        public Nullable<bool> STUDENTS { get; set; }
        public Nullable<bool> FORMATIONS { get; set; }
        public Nullable<bool> MODULES { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
