//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACH
    {
        public int PROFESSOR_ID { get; set; }
        public int FORMATION_ID { get; set; }
    }
}
